### PR TITLE
Add isomorphic-style-loader

### PR DESCRIPTION
**Pull request by koistya**
[isomorphic-style-loader](https://github.com/kriasoft/isomorphic-style-loader/) for Webpack - allows to extract critical CSS for any given page/screen in React apps and inline it into HTML during server-side rendering (SSR). See [React Starter Kit](https://github.com/kriasoft/react-starter-kit) as an example.

### CODE REVIEW

**Comment by pocketjoso** [comment]
Cool! How does your tool define critical css? All css needed for all modules used on a certain page?

**Comment by addyosmani** [comment]
This sounds like a useful addition from the description. Same question as @pocketjoso above. Could you describe how critical css is approached in the project linked up?

**Comment by koistya** [comment]
When web page (screen) of a React app is rendered on the server, with `isomorphic-style-loader` for Webpack it's super easy to collect all the CSS used for rendering of that particular page and embed that into the HTML. Here is an example:

##### Server-side rendering of React app in Node.js

```js
import express from 'express';
import { renderToString } from 'react-dom';
import router from './router.js'; // <-- isomorphic router, see react-starter-kit

const server = express();
const port = process.env.PORT || 3000;

// Server-side rendering of the React app
server.get('*', async (req, res, next) => {
  try {
    const css = [];
    const context = { insertCss: (styles) => css.push };
    await router.dispatch({ ...req, context }, (component, state) => {
      const body = renderToString(component);
      const html = `<!doctype html>
        <html>
          <head>
            <script async src="/client.js"></script>
            <style>${css.join('')}</style>
          </head>
          <body>
            <div id="root">${body}</div>
          </body>
        </html>`
      res.status(state.status).send(html);
    });
  } catch (err) {
    next(err);
  }
});

server.listen(3000, () => {
  console.log(`Node.js app is running at http://localhost:${port}/`);
});
```

##### React component example

```css
.root { color: red; }
```

```js
import React from 'react';
import withStyles from './withStyles.js';
import s from './MyComponent.scss';

function MyComponent(props) {
  return <div className={s.root}>Hello, world!</div>;
}

export default withStyles(MyComponent, s);
```

**Comment by pocketjoso** [comment]
Okay, looks cool! Not ideal to inline css for the whole page, but better than not using critical css at all.

So this generates the critical css on the fly for each request, thereby handling dynamic content correctly (as you have access to thing like the logged in user etc)? Does it slow down the server response time?

**Comment by koistya** [comment]
pocketjoso it doesn't add any overhead to what is already implied by rendering React components on the server. Basically it just boils down to `var css = []; css.push(...); css.push(); css.join('');` during server-side rendering, because each React component already contains a compiled version of its own peace of CSS generated during bundling & optimization stage (by Webpack), as well as automatically generated class names (e.g. `<div class="f3c j12">..</div>`, generated by PostCSS) if case you're using CSS Modules.

**Comment by pocketjoso** [comment]
@addyosmani I think this is a good addition to this Repo then. :)

**Comment by addyosmani** [comment]
:+1:

**Pull request merged**
